[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "v3"
  name = "github.com/AntoniBertel/telebot"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/sfreiberg/gotwilio"

